#ifndef _VULKAN_FORMAT_HPP_
#define _VULKAN_FORMAT_HPP_

#include <vulkan/vulkan.h>

const VkFormat VULKAN_FORMATS[] =
{
	VK_FORMAT_B8G8R8A8_UNORM,
	VK_FORMAT_R8G8B8A8_UNORM,
	VK_FORMAT_R32G32B32A32_SFLOAT,
	VK_FORMAT_R32_SFLOAT,
	VK_FORMAT_R32G32B32_SFLOAT // FIX THIS
};

#endif
