#ifndef _GRAPHICS_SETTINGS_HPP_
#define _GRAPHICS_SETTINGS_HPP_

#define ETERNAL_USE_DXMATH_TYPES

#define FRAME_LAG					(2)
#define MAX_VERTICES_BUFFERS		(8)
#define MAX_RENDER_TARGETS			(8)
#define UPLOAD_BUFFER_SIZE			(32768)

#endif
